///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesAppLogo = 'assets/images/app_logo.png';
  static const String imagesLogo = 'assets/images/logo.svg';
  static const String imagesPlant = 'assets/images/plant.svg';
  static const String imagesSplashBottom = 'assets/images/splash_bottom.svg';
  static const String imagesPageViewBackGround1 = 'assets/images/pageViewBackGround1.svg';
  static const String imagesPageViewBackGround2 = 'assets/images/pageViewBackGround2.svg';
  static const String imagesPageViewImg1 = 'assets/images/pageViewImg1.svg';
  static const String imagesPageViewImg2 = 'assets/images/pageViewImg2.svg';
  static const String googleLogo = 'assets/images/google-icon.svg';
  static const String facebookLogo = 'assets/images/facebook-icon.svg';
  static const String appleLogo = 'assets/images/apple-icon.svg';
  static const String checkIcon = 'assets/images/Check.svg';

}
