name: fruits_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #win32: ^5.0.0 # Or a compatible version for your Dart SDK
  flutter_svg: ^2.0.10+1
  flutter_localization:
  cupertino_icons: ^1.0.6
  dots_indicator: ^2.1.1
  shared_preferences: ^2.2.3
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.1.1
  dartz: ^0.10.1
  firebase_auth: ^5.1.1
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  modal_progress_hud_nsn: ^0.5.1
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  cloud_firestore: ^5.4.4
  flutter_svg_provider: ^1.0.7
  skeletonizer: ^1.4.2
  equatable: ^2.0.7
  loading_animation_widget: ^1.3.0
  http: ^1.3.0
  flutter_paypal_payment: ^1.0.8
  uuid: ^4.5.1
  timeline_tile: ^2.0.0
  supabase_flutter: ^2.8.1
  image_picker: ^1.1.2








dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - lang/ar.json
    - lang/en.json
    - assets/images/google-icon.svg
    - assets/images/apple-icon.svg
    - assets/images/facebook-icon.svg
    - assets/images/Check.svg




  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700






flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

