// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHLXM7vyuOAQ3ya_jv1eAK4xOl1wGOjAU',
    appId: '1:601256712185:web:66533fd931da6e3eb70f28',
    messagingSenderId: '601256712185',
    projectId: 'fruit-app-e8442',
    authDomain: 'fruit-app-e8442.firebaseapp.com',
    storageBucket: 'fruit-app-e8442.appspot.com',
    measurementId: 'G-NDFQGL2ZN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4vCeFfeD4HyMrW0kDq1TmPmAwc39_3fY',
    appId: '1:601256712185:android:8fe092d98062f8d9b70f28',
    messagingSenderId: '601256712185',
    projectId: 'fruit-app-e8442',
    storageBucket: 'fruit-app-e8442.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDllhcJPZ1lWuAXM7e-ktNqnr_4TYD-k58',
    appId: '1:601256712185:ios:3a10a03a3ac3b6eab70f28',
    messagingSenderId: '601256712185',
    projectId: 'fruit-app-e8442',
    storageBucket: 'fruit-app-e8442.appspot.com',
    iosBundleId: 'com.example.fruitsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDllhcJPZ1lWuAXM7e-ktNqnr_4TYD-k58',
    appId: '1:601256712185:ios:cc845950ed3be285b70f28',
    messagingSenderId: '601256712185',
    projectId: 'fruit-app-e8442',
    storageBucket: 'fruit-app-e8442.appspot.com',
    iosBundleId: 'com.example.fruitsApp.RunnerTests',
  );
}
